Create README_courier-dovecot-migrate.pl.md
dovecot/tools pull request #2
Opened 2023-09-02 07:33 UTC by rubo77

2023-09-02 12:22 UTC, cmouse requested changes

2023-09-02 12:22 UTC, cmouse commented on README_courier-dovecot-migrate.pl.md
> +**WARNING: Badly done migration will cause your IMAP and/or POP3 clients to re-download all mails. Read [Migration](https://web.archive.org/web/20161208093331/http://wiki.dovecot.org/Migration) page
Please use https://doc.dovecot.org/admin_manual/migrating_mailboxes/

2023-09-02 12:22 UTC, cmouse commented on README_courier-dovecot-migrate.pl.md
> +[courier-dovecot-migrate.pl](https://web.archive.org/web/20161208093331/http://www.dovecot.org/tools/courier-dovecot-migrate.pl) does a perfect migration from Courier IMAP and POP3, preserving IMAP U
Why are you linking to web.archive.org instead of this repo?

2023-09-02 12:22 UTC, cmouse commented on README_courier-dovecot-migrate.pl.md
> +You can also convert each user as they log in for the first time, using [PostLoginScripting](https://web.archive.org/web/20161208093331/http://wiki.dovecot.org/PostLoginScripting) with a script somet
https://doc.dovecot.org/admin_manual/post_login_scripting/

2023-09-02 12:25 UTC, cmouse commented
Thank you for the effort. I do wonder if this belongs to documentation instead. I'll give this a thought.

2023-09-06 04:50 UTC, cmouse commented
I think this page should go into https://doc.dovecot.org/3.0/admin_manual/migrating_mailboxes/courier/ instead. Can you create a pull request at https://github.com/dovecot/documentation instead? Thank you!

2023-09-06 04:50 UTC, closed without merging

2023-09-17 11:56 UTC, rubo77 commented
https://github.com/dovecot/documentation/pull/779